CREATE TABLE PAYLOADVAULT (
    DOCUMENTID INT AUTO_INCREMENT PRIMARY KEY,
	INTERFACE_ID VARCHAR(50),
	SOURCE VARCHAR(50),
	TARGET VARCHAR(50),
	INTERFACE_NAME VARCHAR(50),
	TRACKING_ID VARCHAR(50),
	DOCUMENT_TYPE VARCHAR(50),
    DOCUMENT_NAME VARCHAR(100),
	INSERTED_DATE TIMESTAMP,
	TRANSACTION_ID VARCHAR(50),
	IDENTIFIER1 VARCHAR(50),
	IDENTIFIER2 VARCHAR(50),
	IDENTIFIER3 VARCHAR(50),
	IDENTIFIER4 VARCHAR(50),
    PAYLOAD BLOB
);